data_config:
  root: ./data/spmotif
  transform: null
  b: 0.9
  fg_only: false
  generate: false
  batch_size: 128

backbone_config:
  hidden_dim: 32
  dropout: 0.5
  gc_layer: 2
  bn: false
  use_edge_attr: true

model_config:
  fix_r: false
  init_r: 0.9
  decay_interval: 10
  decay_r: 0.1
  final_r: 0.7
  ext_hidden_dim: 32
  ext_dropout: 0.5
  learn_edge_att: true
  pred_loss_coef: 1
  info_loss_coef: 1

optimizer_config:
  weight_decay: 1.0e-5
  lr: 3.0e-3
  lr_scheduler: null
  lr_decay_steps: 20
  lr_decay_rate: 0.1
  lr_decay_min_lr: 1.0e-5

epochs: 200