data_config:
  root: ./data/spmotif
  transform: null
  b: 0.9
  fg_only: false
  generate: false
  batch_size: 128

backbone_config:
  hidden_dim: 32
  dropout: 0.5
  gc_layer: 2
  bn: false
  use_edge_attr: true
  residual: true
  JK: last
  pooling: mean

model_config:
  ratio: 0.5
  reg: 1
  alpha: 1

optimizer_config:
  epoch_based_backward: true
  weight_decay: 1.0e-5
  lr: 3.0e-3
  lr_scheduler: null
  lr_decay_steps: 20
  lr_decay_rate: 0.1
  lr_decay_min_lr: 1.0e-5

epochs: 5